/**
 * Generates AI context documents and AI-ready prompts for LLM assistants.
 */
'use strict';

const { detectProject } = require('../detectors/project.js');

/**
 * Generate an AI-ready project context document.
 * @param {string} rootDir
 * @param {string} treeText
 * @param {Object} stats
 * @returns {string} markdown
 */
function generateAiContext(rootDir, treeText, stats) {
  const info = detectProject(rootDir);
  const lines = [];

  lines.push(`# AI Context: ${info.name}`, '');
  lines.push(`> This document provides full project context for AI assistants.`, '');

  // Project Info
  lines.push('## Project Info', '');
  lines.push(`| Field | Value |`);
  lines.push(`| :--- | :--- |`);
  lines.push(`| **Name** | ${info.name} |`);
  if (info.language) lines.push(`| **Language** | ${info.language} |`);
  if (info.framework) lines.push(`| **Framework** | ${info.framework} |`);
  if (info.packageManager) lines.push(`| **Package Manager** | ${info.packageManager} |`);
  if (info.runtime) lines.push(`| **Runtime** | ${info.runtime} |`);
  if (info.buildTool) lines.push(`| **Build Tool** | ${info.buildTool} |`);
  if (info.testingFramework) lines.push(`| **Testing** | ${info.testingFramework} |`);
  if (info.linter) lines.push(`| **Linter** | ${info.linter} |`);
  if (info.formatter) lines.push(`| **Formatter** | ${info.formatter} |`);
  if (info.cssFramework) lines.push(`| **CSS** | ${info.cssFramework} |`);
  if (info.database) lines.push(`| **Database** | ${info.database} |`);
  if (info.ci) lines.push(`| **CI/CD** | ${info.ci} |`);
  if (info.containerized) lines.push(`| **Containerized** | Yes (Docker) |`);
  if (info.monorepo) lines.push(`| **Monorepo** | Yes |`);
  lines.push('');

  // Detected tools
  if (info.detectedTools.length > 0) {
    lines.push('## Detected Tools', '');
    lines.push(info.detectedTools.map(t => `- ${t}`).join('\n'));
    lines.push('');
  }

  // Config files
  if (info.configFiles.length > 0) {
    lines.push('## Configuration Files', '');
    lines.push(info.configFiles.map(f => `- \`${f}\``).join('\n'));
    lines.push('');
  }

  // Scripts
  if (Object.keys(info.scripts).length > 0) {
    lines.push('## Scripts', '');
    lines.push('```json');
    lines.push(JSON.stringify(info.scripts, null, 2));
    lines.push('```', '');
  }

  // Dependencies
  if (Object.keys(info.dependencies).length > 0) {
    lines.push('## Dependencies', '');
    for (const [name, ver] of Object.entries(info.dependencies)) {
      lines.push(`- \`${name}\`: ${ver}`);
    }
    lines.push('');
  }

  if (Object.keys(info.devDependencies).length > 0) {
    lines.push('## Dev Dependencies', '');
    for (const [name, ver] of Object.entries(info.devDependencies)) {
      lines.push(`- \`${name}\`: ${ver}`);
    }
    lines.push('');
  }

  // Statistics
  lines.push('## Statistics', '');
  lines.push(`- Directories: ${stats.dirs}`);
  lines.push(`- Files: ${stats.files}`);
  if (stats.totalSizeText) lines.push(`- Total size: ${stats.totalSizeText}`);
  if (stats.largestFile) lines.push(`- Largest file: ${stats.largestFile.name} (${require('../core/formatter.js').formatSize(stats.largestFile.size)})`);
  lines.push(`- Max depth: ${stats.maxDepth}`);
  lines.push('');

  // Language breakdown
  if (stats.languageBreakdown && stats.languageBreakdown.length > 0) {
    lines.push('## Language Breakdown', '');
    lines.push('| Language | Files | % |');
    lines.push('| :--- | :--- | :--- |');
    stats.languageBreakdown.forEach(({ lang, count, pct }) =>
      lines.push(`| ${lang} | ${count} | ${pct}% |`));
    lines.push('');
  }

  // Folder structure
  lines.push('## Folder Structure', '');
  lines.push('```');
  lines.push(treeText);
  lines.push('```', '');

  lines.push(`---`, '');
  lines.push(`_Generated by project-tree-md on ${new Date().toISOString()}_`);

  return lines.join('\n');
}

/**
 * Generate an AI-ready prompt for ChatGPT/Claude/Gemini.
 * @param {string} rootDir
 * @param {string} treeText
 * @param {Object} stats
 * @returns {string}
 */
function generateAiPrompt(rootDir, treeText, stats) {
  const info = detectProject(rootDir);
  const parts = [];

  parts.push(`I have a${info.framework ? ` ${info.framework}` : ''} project called "${info.name}"${info.language ? ` written in ${info.language}` : ''}.`);
  if (info.buildTool) parts.push(`It uses ${info.buildTool} as its build tool.`);
  if (info.packageManager) parts.push(`Package manager: ${info.packageManager}.`);
  if (info.database) parts.push(`Database: ${info.database}.`);
  if (info.testingFramework) parts.push(`Testing: ${info.testingFramework}.`);

  parts.push('');
  parts.push('Here is the project structure:');
  parts.push('```');
  parts.push(treeText);
  parts.push('```');

  if (Object.keys(info.scripts).length > 0) {
    parts.push('');
    parts.push('Available scripts:');
    for (const [k, v] of Object.entries(info.scripts)) {
      parts.push(`- ${k}: ${v}`);
    }
  }

  const topDeps = Object.keys(info.dependencies).slice(0, 15);
  if (topDeps.length > 0) {
    parts.push('');
    parts.push('Key dependencies: ' + topDeps.join(', '));
  }

  parts.push('');
  parts.push(`Stats: ${stats.statsText}`);
  parts.push('');
  parts.push('---');
  parts.push('Please help me with: [YOUR REQUEST HERE]');

  return parts.join('\n');
}

module.exports = { generateAiContext, generateAiPrompt };
