/**
 * AI Rules Generator Module
 *
 * Generates tailored system prompt guidelines (.cursorrules, AGENTS.md, copilot-instructions.md)
 * customized to the target codebase's detected frameworks, language stack, and architecture.
 */
'use strict';

const fs = require('fs');
const path = require('path');
const { detectProject } = require('../detectors/project.js');
const { scan } = require('../core/scanner.js');

/**
 * Generate AI agent rules and coding guidelines based on project inspection.
 *
 * @param {string} dirPath
 * @param {object} [options]
 * @returns {string}
 */
function generateAiRules(dirPath, options = {}) {
  const absolutePath = path.resolve(dirPath);
  const proj = detectProject(absolutePath);
  const rootNode = scan(absolutePath, { maxDepth: 2 });
  const projName = proj.name || path.basename(absolutePath);

  const frameworks = proj.frameworks || [];
  const mainLang = Object.keys(proj.languages || {}).reduce((a, b) =>
    (proj.languages[a] > (proj.languages[b] || 0) ? a : b), 'JavaScript');

  let rules = [];

  rules.push(`# AI Agent Coding Guidelines & Context for ${projName}`);
  rules.push(``);
  rules.push(`> Automatically generated by project-tree-md v3.2`);
  rules.push(``);
  rules.push(`## 📌 Project Overview`);
  rules.push(`- **Project Name**: \`${projName}\``);
  rules.push(`- **Primary Language**: ${mainLang}`);
  rules.push(`- **Frameworks & Tech Stack**: ${frameworks.length ? frameworks.join(', ') : 'Node.js / Standard Library'}`);
  if (proj.entryPoint) rules.push(`- **Entry Point**: \`${proj.entryPoint}\``);
  if (proj.packageManager) rules.push(`- **Package Manager**: \`${proj.packageManager}\``);
  rules.push(``);

  rules.push(`## ⚙️ Architecture & Coding Standards`);

  if (frameworks.includes('Next.js')) {
    rules.push(`- **Next.js**: Use App Router conventions. Prefer Server Components by default; use \`'use client'\` sparingly. Keep UI modular in \`components/\`.`);
  }
  if (frameworks.includes('React') || frameworks.includes('React Native')) {
    rules.push(`- **React**: Use functional components with custom hooks. Keep state localized where possible. Follow modular component separation.`);
  }
  if (frameworks.includes('Vue') || frameworks.includes('Nuxt.js')) {
    rules.push(`- **Vue**: Use Composition API with \`<script setup>\`. Keep state cleanly scoped.`);
  }
  if (frameworks.includes('Express') || frameworks.includes('NestJS')) {
    rules.push(`- **Backend Services**: Maintain clean separation of routes, controllers, services, and middlewares. Handle exceptions gracefully with standard HTTP status codes.`);
  }
  if (frameworks.includes('Flutter')) {
    rules.push(`- **Flutter/Dart**: Follow BLoC or Provider state management patterns. Keep UI widgets decoupled from business logic.`);
  }
  if (frameworks.includes('Django') || frameworks.includes('FastAPI')) {
    rules.push(`- **Python Backend**: Follow PEP 8 style standards. Type annotate function parameters and return values.`);
  }

  rules.push(`- **Zero-Unused-Imports**: Keep imports clean and remove unused modules.`);
  rules.push(`- **Error Handling**: Always handle async promises and stream errors safely without swallowing exceptions.`);
  rules.push(`- **Testing**: Ensure all new features or bug fixes have corresponding unit tests before committing.`);
  rules.push(``);

  rules.push(`## 📁 Project Structure Snapshot`);
  rules.push(`\`\`\``);
  if (rootNode && rootNode.children) {
    for (const child of rootNode.children.slice(0, 15)) {
      rules.push(`${child.name}${child.children ? '/' : ''}`);
    }
  }
  rules.push(`\`\`\``);

  return rules.join('\n');
}

module.exports = {
  generateAiRules,
};
