'use strict';

/**
 * Markdown exporter — generates PROJECT_STRUCTURE.md content.
 * @param {string}  treeText    Plain-text tree
 * @param {Object}  stats       Output of computeStats()
 * @param {Object}  [projectInfo]  Output of detectProject() (optional)
 * @returns {string} markdown
 */
function toMarkdown(treeText, stats, projectInfo = null) {
  const dateStr = new Date().toISOString().replace('T', ' ').slice(0, 19) + ' UTC';
  const titleName = (projectInfo && projectInfo.name) ? projectInfo.name : 'Project Structure';

  const lines = [
    `# 📁 ${titleName}`,
    '',
    `> ⚡ **Generated by \`project-tree-md\`** &nbsp;|&nbsp; 📅 **${dateStr}**`,
    '',
    '### 📊 Project Overview',
    '',
    '| Property | Details |',
    '| :--- | :--- |',
    `| 📁 **Directories** | \`${(stats && stats.dirs !== undefined) ? stats.dirs : (stats.foldersCount || 0)}\` |`,
    `| 📄 **Files** | \`${(stats && stats.files !== undefined) ? stats.files : (stats.filesCount || 0)}\` |`,
  ];

  if (projectInfo) {
    if (projectInfo.language) lines.push(`| 🔤 **Language** | \`${projectInfo.language}\` |`);
    if (projectInfo.packageManager) lines.push(`| 📦 **Package Manager** | \`${projectInfo.packageManager}\` |`);
    if (projectInfo.framework) lines.push(`| ⚙️ **Framework** | \`${projectInfo.framework}\` |`);
    if (projectInfo.runtime) lines.push(`| 🚀 **Runtime** | \`${projectInfo.runtime}\` |`);
  }

  lines.push(
    '',
    '### 🌴 Directory Tree',
    '',
    '```text',
    treeText,
    '```',
    '',
    '---',
    '_Generated automatically with [project-tree-md](https://github.com/SKThakor137/project-tree-md)_'
  );

  return lines.join('\n');
}

module.exports = { toMarkdown };
