'use strict';

/**
 * YAML exporter — generates YAML from the project tree.
 *
 * Manual serializer — no third-party YAML library.
 * Zero dependencies.
 */

/**
 * Escape a YAML string value if it contains special characters.
 *
 * @param {string} str
 * @returns {string}
 */
function yamlString(str) {
  if (!str && str !== '') return '""';
  const s = String(str);
  // Quote if contains special chars, starts with special, or could be interpreted as non-string
  if (/[:{}\[\],&*#?|<>=!%@`\n\r]/.test(s) ||
      /^[-?:]\s/.test(s) ||
      /^(true|false|null|yes|no|on|off)$/i.test(s) ||
      /^\d/.test(s) ||
      s.startsWith(' ') || s.endsWith(' ') ||
      s === '') {
    return '"' + s.replace(/\\/g, '\\\\').replace(/"/g, '\\"').replace(/\n/g, '\\n') + '"';
  }
  return s;
}

/**
 * Convert a ScanNode to YAML string recursively.
 *
 * @param {Object} node — ScanNode
 * @param {number} [indent=0]
 * @returns {string}
 */
function nodeToYaml(node, indent = 0) {
  const pad = ' '.repeat(indent);
  const isDir = node.children !== undefined;
  const lines = [];

  lines.push(`${pad}- name: ${yamlString(node.name)}`);
  lines.push(`${pad}  type: ${isDir ? 'directory' : 'file'}`);

  if (!isDir) {
    if (node.size !== undefined) lines.push(`${pad}  size: ${node.size}`);
    if (node.ext) lines.push(`${pad}  extension: ${yamlString(node.ext)}`);
    if (node.lineCount) lines.push(`${pad}  lines: ${node.lineCount}`);
    if (node.isBinary) lines.push(`${pad}  binary: true`);
  }

  if (node.isSensitive) lines.push(`${pad}  sensitive: true`);
  if (node.isSymlink) {
    lines.push(`${pad}  symlink: true`);
    if (node.symlinkTarget) lines.push(`${pad}  target: ${yamlString(node.symlinkTarget)}`);
  }
  if (node.isEmpty) lines.push(`${pad}  empty: true`);
  if (node.collapsed) {
    lines.push(`${pad}  collapsed: true`);
    lines.push(`${pad}  collapsedCount: ${node.collapsedCount || 0}`);
  }
  if (node.summary) lines.push(`${pad}  summary: ${yamlString(node.summary)}`);

  if (isDir && node.children && node.children.length > 0) {
    lines.push(`${pad}  children:`);
    for (const child of node.children) {
      lines.push(nodeToYaml(child, indent + 4));
    }
  }

  return lines.join('\n');
}

/**
 * Export tree as YAML string.
 *
 * @param {Object} tree — ScanNode root
 * @param {Object} [stats] — optional stats
 * @returns {string}
 */
function toYaml(tree, stats = {}) {
  const lines = ['# Project Tree — generated by project-tree-md', '---'];

  if (stats.dirs !== undefined || stats.files !== undefined) {
    lines.push('metadata:');
    if (stats.dirs !== undefined) lines.push(`  directories: ${stats.dirs}`);
    if (stats.files !== undefined) lines.push(`  files: ${stats.files}`);
    if (stats.totalSize !== undefined) lines.push(`  totalSize: ${stats.totalSize}`);
    if (stats.maxDepth !== undefined) lines.push(`  maxDepth: ${stats.maxDepth}`);
    lines.push('');
  }

  lines.push('tree:');
  lines.push(nodeToYaml(tree, 2));

  return lines.join('\n') + '\n';
}

module.exports = { toYaml, yamlString };
